version: '3.9'

services:
  api:
    container_name: api_project_full_stack
    build: .
    ports:
      - 3000:3001
    environment:
      - DB_HOST=db
      - DB_USER=luish
      - DB_PASSWORD=1234
      - DB=project_fullstack
      - SECRET_KEY=chaveultrasecreta
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=luish
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=project_fullstack
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U luish -d project_fullstack"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 5s
    volumes:
      - postgres_project:/var/lib/postgresql/data

volumes:
  postgres_project:
    driver: local
